#!/usr/bin/env bash

set -Eeuxo pipefail

pushd "$(dirname "$0")" >/dev/null

go mod tidy
# Create fully static binaries to avoid any compatibility issues and allow extremely simple download-and-run usage.
CGO_ENABLED=0 go build -o journald-exporter-oci

popd >/dev/null
